recipe: default.v1
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: null
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

assistant_id: 20250306-104622-acyclic-landing
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100

action_endpoint:
  url: "http://localhost:5055/webhook"

