recipe: default.v1
language: en
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 50
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 50
policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 50
assistant_id: 20250304-160348-chunky-pulse
