version: '3.0'
services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - "rasa-actions"
    environment:
      - RASA_ACTION_ENDPOINT=http://rasa-actions:5055/webhook
    networks:
      - rasa-network

  rasa-actions:
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    networks:
      - rasa-network

networks:
  rasa-network:
    driver: bridge